### PR TITLE
Pull request for New York Times website clone - HTML & CSS

### PR DESCRIPTION
**Pull request by shubham14p3**
- Updated CSS
- Updated HTML
- Updated the W3Validation
- Fixed Icon Issue
- Fixed Youtube, Image Positioning

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
Pull Request under review by David Elí 👨‍💻

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi Team. 😄 
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****
### Readme.
- [ ] Readme.
Use a descriptive Readme, fill the descriptive fields.
****
### Pull Request & Commits.

- [ ] Please write a meaningful title and a short description of the work you did in general terms.

****
### Project.

- [ ] HTML Validator.
We have some issues on the validator, please fix it.

Screen Shot 2020-03-07 at 6 07 42 PM

- [ ] Inline Styling.
It is not permitted the use of inline styling because of its considered a bad practice.
Instead, implement a class and modify using CSS.
More info on this [article](https://speckyboy.com/good-bad-css-practices). 

Screen Shot 2020-03-07 at 6 11 40 PM

****
### Navbar.

- [ ] The navbar should have a fixed position (it sticks to the top part of the screen).

****
### Footer.

- [ ] The footer should use 100% of the width of the container and be centered.
Image below. ⬇️ 

Screen Shot 2020-03-07 at 6 21 25 PM

****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by ybadmus** [comment]
Hello,


We fixed all issues but the dashboard won't allow is to submit for another
review.

The is the new url of our pull request
https://github.com/shubham14p3/newyork-times-clone/pull/2   please review
and advise.

Best Regards,
Yusuf

**Comment by ybadmus** [comment]
Hello,


We fixed all issues but the dashboard won't allow is to submit for another
review.

This is the new URL of our pull request
https://github.com/shubham14p3/newyork-times-clone/pull/2 please review and
advise.

Best Regards,
Yusuf

**Pull request merged**
